-- Code generated by sqldefkit; DO NOT EDIT.

-- source: orders.sql
-- Mutually references users, forming a dependency cycle sqldefkit
-- splits automatically by moving the foreign key to an ALTER TABLE.
CREATE TABLE orders (
    id serial PRIMARY KEY,
    user_id integer NOT NULL
);

-- source: users.sql
-- References orders back, closing the cycle with orders.sql.
CREATE TABLE users (
    id serial PRIMARY KEY,
    email text NOT NULL UNIQUE,
    favorite_order_id integer
);

-- source: orders.sql
-- fk constraint moved by sqldefkit to break a dependency cycle (from orders.sql)
ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users (id);

-- source: users.sql
-- fk constraint moved by sqldefkit to break a dependency cycle (from users.sql)
ALTER TABLE users ADD FOREIGN KEY (favorite_order_id) REFERENCES orders (id);
