package bundle

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, dir, rel, content string) {
	t.Helper()
	path := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestDiscoverFiles_SortedAndSkipsHidden(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "b/two.sql", "SELECT 1;")
	writeFile(t, dir, "a.sql", "SELECT 1;")
	writeFile(t, dir, "b/one.sql", "SELECT 1;")
	writeFile(t, dir, ".hidden/skip.sql", "SELECT 1;")
	writeFile(t, dir, "notsql.txt", "nope")

	files, err := DiscoverFiles(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{"a.sql", "b/one.sql", "b/two.sql"}
	if strings.Join(files, ",") != strings.Join(want, ",") {
		t.Errorf("files = %v, want %v", files, want)
	}
}

func TestDiscoverFiles_ErrorWhenNoneFound(t *testing.T) {
	dir := t.TempDir()
	_, err := DiscoverFiles(dir)
	if err == nil {
		t.Fatal("expected error for empty directory")
	}
}

// TestBuild_EndToEnd exercises: comments preceding statements, an FK from
// orders -> users where users is defined in a file that sorts later
// lexicographically, and a view that requires a directive to pick up its
// dependency, asserting the exact byte-for-byte output.
func TestBuild_EndToEnd(t *testing.T) {
	dir := t.TempDir()

	// "orders.sql" sorts before "users.sql", but orders depends on
	// users via FK, so users must be emitted first despite file order.
	writeFile(t, dir, "orders.sql", `-- orders table
CREATE TABLE orders (
	id int PRIMARY KEY,
	user_id int REFERENCES users(id)
);`)

	writeFile(t, dir, "users.sql", `CREATE TABLE users (
	id int PRIMARY KEY,
	name text
);`)

	// View depends on orders via a directive (view body dependency
	// extraction is best-effort and this form isn't auto-detected).
	writeFile(t, dir, "views.sql", `-- sqldefkit:require orders
CREATE VIEW order_count AS SELECT count(*) FROM orders;`)

	out, err := Build(dir, Postgres, os.ReadFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := `-- Code generated by sqldefkit; DO NOT EDIT.

-- source: users.sql
CREATE TABLE users (
	id int PRIMARY KEY,
	name text
);

-- source: orders.sql
-- orders table
CREATE TABLE orders (
	id int PRIMARY KEY,
	user_id int REFERENCES users(id)
);

-- source: views.sql
-- sqldefkit:require orders
CREATE VIEW order_count AS SELECT count(*) FROM orders;
`
	if string(out) != want {
		t.Errorf("output mismatch\n--- got ---\n%s\n--- want ---\n%s", out, want)
	}
}

func TestBuild_DuplicateDefinitionError(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.sql", `CREATE TABLE users (id int);`)
	writeFile(t, dir, "b.sql", `CREATE TABLE users (id int);`)

	_, err := Build(dir, Postgres, os.ReadFile)
	if err == nil {
		t.Fatal("expected duplicate definition error")
	}
	msg := err.Error()
	if !strings.Contains(msg, "a.sql") || !strings.Contains(msg, "b.sql") {
		t.Errorf("error message = %q, expected both file names", msg)
	}
}

func TestBuild_CycleError(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.sql", `CREATE TABLE a (id int, b_id int REFERENCES b(id));`)
	writeFile(t, dir, "b.sql", `CREATE TABLE b (id int, a_id int REFERENCES a(id));`)

	_, err := Build(dir, Postgres, os.ReadFile)
	if err == nil {
		t.Fatal("expected cycle error")
	}
}

func TestBuild_DeterministicAcrossRuns(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "orders.sql", `CREATE TABLE orders (id int, user_id int REFERENCES users(id));`)
	writeFile(t, dir, "users.sql", `CREATE TABLE users (id int);`)
	writeFile(t, dir, "misc.sql", `CREATE TABLE misc (id int);`)

	var prev []byte
	for i := 0; i < 5; i++ {
		out, err := Build(dir, Postgres, os.ReadFile)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if prev != nil && string(prev) != string(out) {
			t.Fatalf("non-deterministic output across runs:\n%s\n---\n%s", prev, out)
		}
		prev = out
	}
}

// TestBuild_CRLFInputNormalized verifies that source files with CRLF line
// endings (e.g. checked out on Windows with autocrlf) produce byte-identical
// output to their LF equivalents: line endings are normalized to LF right
// after reading, before lexing.
func TestBuild_CRLFInputNormalized(t *testing.T) {
	const usersLF = "-- users table\nCREATE TABLE users (\n\tid int PRIMARY KEY\n);\n"
	const ordersLF = "CREATE TABLE orders (\n\tid int,\n\tuser_id int REFERENCES users(id)\n);\n"

	lfDir := t.TempDir()
	writeFile(t, lfDir, "orders.sql", ordersLF)
	writeFile(t, lfDir, "users.sql", usersLF)

	crlfDir := t.TempDir()
	writeFile(t, crlfDir, "orders.sql", strings.ReplaceAll(ordersLF, "\n", "\r\n"))
	writeFile(t, crlfDir, "users.sql", strings.ReplaceAll(usersLF, "\n", "\r\n"))

	lfOut, err := Build(lfDir, Postgres, os.ReadFile)
	if err != nil {
		t.Fatalf("unexpected error (LF): %v", err)
	}
	crlfOut, err := Build(crlfDir, Postgres, os.ReadFile)
	if err != nil {
		t.Fatalf("unexpected error (CRLF): %v", err)
	}

	if string(lfOut) != string(crlfOut) {
		t.Errorf("CRLF input produced different output\n--- LF ---\n%q\n--- CRLF ---\n%q", lfOut, crlfOut)
	}
	if strings.Contains(string(crlfOut), "\r") {
		t.Errorf("output from CRLF input contains carriage returns: %q", crlfOut)
	}
}

func TestBuild_NoTrailingSemicolonFileStillTerminated(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.sql", `CREATE TABLE a (id int)`) // no trailing ';'

	out, err := Build(dir, Postgres, os.ReadFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasSuffix(string(out), "CREATE TABLE a (id int);\n") {
		t.Errorf("output = %q", out)
	}
}
