package bundle

import (
	"strings"

	"github.com/Lazialize/sqldefkit/internal/graph"
)

const header = "-- Code generated by sqldefkit; DO NOT EDIT.\n"

// emit renders the final bundle text from the topologically ordered graph
// nodes, looking up each node's full statement (comments + text) by
// (file, index, subIndex).
func emit(ordered []graph.Node, byKey map[string]statement) []byte {
	var b strings.Builder
	b.WriteString(header)

	lastFile := ""
	for i, n := range ordered {
		s := byKey[keySub(n.File, n.Index, n.SubIndex)]

		if i == 0 || s.file != lastFile {
			b.WriteString("\n-- source: ")
			b.WriteString(s.file)
			b.WriteString("\n")
			lastFile = s.file
		} else {
			b.WriteString("\n")
		}

		if s.synthesized {
			b.WriteString("-- fk constraint moved by sqldefkit to break a dependency cycle (from ")
			b.WriteString(s.synthesizedFrom)
			b.WriteString(")\n")
		}

		for _, c := range s.ps.LeadingComments {
			b.WriteString(c)
			b.WriteString("\n")
		}
		b.WriteString(s.ps.Text)
		b.WriteString(";\n")
	}

	return []byte(b.String())
}
