-- Code generated by sqldefkit; DO NOT EDIT.

-- source: products.sql
-- Sellable products.
CREATE TABLE products (
    id serial PRIMARY KEY,
    name text NOT NULL
);

-- source: users.sql
-- Application users.
CREATE TABLE users (
    id serial PRIMARY KEY,
    email text NOT NULL UNIQUE
);

-- source: orders.sql
-- Sorts before products.sql and users.sql lexicographically, but
-- references both, so it must be reordered after them in output.
CREATE TABLE orders (
    id serial PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    product_id integer NOT NULL REFERENCES products(id)
);

CREATE INDEX orders_user_id_idx ON orders (user_id);

-- source: views.sql
-- users is only reachable here via a parenthesized subquery, which the
-- best-effort FROM/JOIN scanner does not descend into, so it must be
-- declared explicitly.
-- sqldefkit:require users
CREATE VIEW order_summary AS
SELECT
    o.id AS order_id,
    (SELECT email FROM users u WHERE u.id = o.user_id) AS user_email,
    p.name AS product_name
FROM orders o
JOIN products p ON p.id = o.product_id;
